"""widen odepa unidad to 100

ID de revisión: 673b9fe338cd
Revisión anterior: 8f2a4c7e1d90
Fecha: 2026-07-11 15:36:41.379268
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic.
revision: str = '673b9fe338cd'
down_revision: str | None = '8f2a4c7e1d90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odepa_prices', schema=None) as batch_op:
        batch_op.alter_column('unidad',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odepa_prices', schema=None) as batch_op:
        batch_op.alter_column('unidad',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
