"""unique_constraint_odepa

ID de revisión: 9fad6bdb1443
Revisión anterior: c9acd3385f90
Fecha: 2026-06-19 20:34:21.585620
"""
from collections.abc import Sequence

from alembic import op

# Identificadores de revisión usados por Alembic.
revision: str = '9fad6bdb1443'
down_revision: str | None = 'c9acd3385f90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odepa_prices', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_odepa_producto_mercado_fecha', ['producto', 'mercado', 'fecha'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odepa_prices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_odepa_producto_mercado_fecha', type_='unique')

    # ### end Alembic commands ###
