"""add consultation_history

ID de revisión: ab2a98397321
Revisión anterior: 52257cb43405
Fecha: 2026-07-24 02:03:27.277016
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic.
revision: str = 'ab2a98397321'
down_revision: str | None = '52257cb43405'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
