"""initial

ID de revisión: c9acd3385f90
Revisión anterior: None
Fecha: 2026-06-18 23:10:15.186446
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Identificadores de revisión usados por Alembic.
revision: str = 'c9acd3385f90'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('intent', sa.String(length=20), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultations_phone_hash'), ['phone_hash'], unique=False)

    op.create_table('odepa_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('mercado', sa.String(length=200), nullable=False),
    sa.Column('precio_kg', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fuente', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odepa_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odepa_prices_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_odepa_prices_mercado'), ['mercado'], unique=False)
        batch_op.create_index(batch_op.f('ix_odepa_prices_producto'), ['producto'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odepa_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odepa_prices_producto'))
        batch_op.drop_index(batch_op.f('ix_odepa_prices_mercado'))
        batch_op.drop_index(batch_op.f('ix_odepa_prices_fecha'))

    op.drop_table('odepa_prices')
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultations_phone_hash'))

    op.drop_table('consultations')
    # ### end Alembic commands ###
